config/routes.rb
Moodapp::Application.routes.draw do
  resources :surveys

  root :to => 'locations#index'
  #match 'dashboard' => 'home#dashboard'

  devise_for :users
  resources :users
  put '/user_admin' => 'users#update', :as => 'user_admin'

  resources :locations do
    collection do
      get 'bulk_edit'
      post 'bulk_confirm'
      post 'bulk_perform'
    end
    member do
      get 'options'
      get 'stats'
      get 'ping'
    end
  end

  resources :locations

  resources :votes

  get "/ipad" => "ipad#index", :as => :ipad
  get "/ipad/configure" => "ipad#configure", :as => :ipad_configuration
  get "/ipad/new_session" => "ipad#new_session"
  post "/ipad/sign_in" => "ipad#sign_in"
  post "/ipad/save_configuration" => "ipad#save_configuration"
  delete "/ipad/logout" => "ipad#logout"


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  # attr_accessible :title, :body
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  # def index
  #   @users = User.all
  # end

  def show
    @user = User.find(params[:id])
  end

  def update
    Rails.logger.info params.inspect
    @user = User.find(params[:user][:id])
    @user.update_attributes(params[:user])
    render :json => @user
  end
end

app/views/users/index.html.erb
<% content_for :page_title do %>
  <h1>Users</h1>
<% end %>

<%= render :partial => 'layouts/notifications'%>

<table class="aui">
  <thead>
    <tr>
      <th class="admin-col">Administrator</th>
      <th>Email</th>
      <th>Created date</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td class="admin-col">
        <%= form_for(user, :url => user_admin_path, :html => { :method => :put, :class => 'user-row' }, :remote => true) do |f| %>
          <%= f.hidden_field :id %>
          <% if user.email == current_user.email %>
          <%= f.check_box :admin, :class => 'checkbox', :disabled => 'disabled' %>
          <% else %>
          <%= f.check_box :admin, :class => 'checkbox' %>
          <% end %>
          <%= f.submit "Save", :class => 'hidden' %>
        <% end %>
      </td>
      <td><%= link_to user.email, user %></td>
      <td><%=l user.created_at.to_date, :format => :long %></td>
      <td>
        <%= link_to 'Destroy', registration_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<script>
  (function($){
    $('form.user-row input[type="checkbox"]').on('change', function(){
      var $this = $(this);
      var $form = $this.parent()
      console.log($this,$form,$this.val());
      $form.find('input[type="submit"]').trigger('click');
    });
  })(AJS.$)
</script>

app/views/users/show.html.erb
<% content_for :page_title do %>
  <ol class="aui-nav aui-nav-breadcrumbs">
    <li><%= link_to "Users", users_path %></li>
  </ol>
  <h1><%=@user.email %></h1>
<% end %>

<%= render :partial => 'layouts/notifications'%>

<p>
  <b>Created at:</b>
  <%=l @user.created_at.to_date, :format => :long%>
</p>