config/routes.rb
Moodapp::Application.routes.draw do
  resources :surveys

  root :to => 'locations#index'
  #match 'dashboard' => 'home#dashboard'

  devise_for :users
  resources :users
  put '/user_admin' => 'users#update', :as => 'user_admin'

  resources :locations do
    collection do
      get 'bulk_edit'
      post 'bulk_confirm'
      post 'bulk_perform'
    end
    member do
      get 'options'
      get 'stats'
      get 'ping'
    end
  end

  resources :locations

  resources :votes

  get "/ipad" => "ipad#index", :as => :ipad
  get "/ipad/configure" => "ipad#configure", :as => :ipad_configuration
  get "/ipad/new_session" => "ipad#new_session"
  post "/ipad/sign_in" => "ipad#sign_in"
  post "/ipad/save_configuration" => "ipad#save_configuration"
  delete "/ipad/logout" => "ipad#logout"


end

app/models/survey.rb
class Survey < ActiveRecord::Base
  validates_presence_of :name, :visual, :question, :scale
  
  attr_accessible :name, :visual, :question, :scale
  
  has_many :locations
  has_many :votes
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.json
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.json
  def update
    @survey = Survey.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey = Survey.find(params[:id])
    #Destroy votes associated with the survey
    @survey.votes.destroy_all
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end
end

app/views/surveys/_form.html.erb
<%= render :partial => 'layouts/notifications'%>

<%= form_for(@survey, :html => {:class => 'aui'}) do |f| %>
  <fieldset>
    <% if @survey.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

        <ul>
        <% @survey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'text' %>
    </div>
    <div class="field-group">
      <%= f.label :question %>
      <%= f.text_field :question, :class => 'text' %>
    </div>
    <div class="group">
      <legend><span>Survey scale</span></legend>
      <div class="radio">
        <%= f.radio_button :scale, 5, :class => 'radio' %>
        <%= f.label :scale_5, "5 values" %>
      </div>
      <div class="radio">
        <%= f.radio_button :scale, 2, :class => 'radio' %>
        <%= f.label :scale_2, "2 values" %>
      </div>
    </div>
    <div class="group">
      <legend><span>Survey visual</span></legend>
      <div class="radio">
        <%= f.radio_button :visual, 'face', :class => 'radio' %>
        <%= f.label :visual_face, "Faces" %>
      </div>
      <div class="radio">
        <%= f.radio_button :visual, 'hand', :class => 'radio' %>
        <%= f.label :visual_hand, "Hands" %>
      </div>
    </div>
  </fieldset>
  <div class="buttons-container">
    <div class="buttons">
      <%= f.submit "Save", :class => 'button submit' %>
      <%= link_to 'Cancel', :back, :class => 'cancel' %>
    </div>
  </div>
<% end %>

app/views/surveys/_index_nosurveys.html.erb
<h2>Create your first survey</h2>
<p>
  Once you have created your surveys you can associate them with the different <%=link_to 'locations', locations_path %><br />
  to display them on your iPads.
</p>
<p>
  <%= link_to 'New Survey', new_survey_path, :class => 'aui-button' %> 
</p>

app/views/surveys/_index_surveys.html.erb
<table class="aui">
  <thead>
    <tr>
      <th>Name</th>
      <th>Question</th>
      <th>Scale</th>
      <th>Visual</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
  <% @surveys.each do |survey| %>
    <tr>
      <td><%= link_to survey.name, survey %></td>
      <td><%= truncate(survey.question, :length => 50) %></td>
      <td><%= survey.scale %></td>
      <td><%= survey.visual %></td>
      <td>
        <%= link_to 'Edit', edit_survey_path(survey) %>
        |
        <%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/surveys/edit.html.erb
<% content_for :page_title do %>
  <h1>Edit <%=@survey.name%></h1>
<% end %>

<% content_for :page_header_image do %>
  <%= image_tag "project-avatar-orange-48@2x.png" %>
<% end %>


<%= render 'form' %>

app/views/surveys/index.html.erb
<% content_for :page_title do %>
  <h1>Surveys</h1>
<% end %>

<% content_for :page_header_image do %>
  <%= image_tag "project-avatar-orange-48@2x.png" %>
<% end %>

<% if @surveys.size > 0 %>
  <% content_for :page_actions do %>
  <%= link_to 'New Survey', new_survey_path, :class => 'aui-button' %>
  <% end %>

  <%= render :partial => 'layouts/notifications'%>
  
  <%= render :partial => 'index_surveys' %>

<% else %>

  <%= render :partial => 'index_nosurveys' %>

<% end %>

app/views/surveys/new.html.erb
<% content_for :page_title do %>
  <h1>New survey</h1>
<% end %>

<% content_for :page_header_image do %>
  <%= image_tag "project-avatar-orange-48@2x.png" %>
<% end %>


<%= render 'form' %>

app/views/surveys/show.html.erb
<% content_for :page_title do %>
  <ol class="aui-nav aui-nav-breadcrumbs">
    <li><%= link_to "Surveys", surveys_path %></li>
  </ol>
  <h1><%=@survey.name%></h1>
<% end %>

<% content_for :page_header_image do %>
  <%= image_tag "project-avatar-orange-48@2x.png" %>
<% end %>


<% content_for :page_actions do %>
<div class="aui-buttons">
  <%= link_to 'Edit', edit_survey_path(@survey), :class => 'aui-button' %>
  <%= link_to 'View votes', votes_path(:survey_id => @survey.id), :class => 'aui-button' %>
  <%= link_to 'Destroy', @survey, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'aui-button aui-button-link' %>
</div>
<% end %>

<%= render :partial => 'layouts/notifications'%>

<p>
  <b>Question:</b>
  <%= @survey.question %>
</p>

<p>
  <b>Scale:</b>
  <%= @survey.scale %>
</p>

<p>
  <b>Visual:</b>
  <%= @survey.visual %>
</p>