config/routes.rb
Moodapp::Application.routes.draw do
  resources :surveys

  root :to => 'locations#index'
  #match 'dashboard' => 'home#dashboard'

  devise_for :users
  resources :users
  put '/user_admin' => 'users#update', :as => 'user_admin'

  resources :locations do
    collection do
      get 'bulk_edit'
      post 'bulk_confirm'
      post 'bulk_perform'
    end
    member do
      get 'options'
      get 'stats'
      get 'ping'
    end
  end

  resources :locations

  resources :votes

  get "/ipad" => "ipad#index", :as => :ipad
  get "/ipad/configure" => "ipad#configure", :as => :ipad_configuration
  get "/ipad/new_session" => "ipad#new_session"
  post "/ipad/sign_in" => "ipad#sign_in"
  post "/ipad/save_configuration" => "ipad#save_configuration"
  delete "/ipad/logout" => "ipad#logout"


end

app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :name, :geography
  
  attr_accessible :active, :geography, :inactive_text, :name, :survey_id, :last_pinged
  
  belongs_to :survey
  has_many :votes
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authenticate_user!, :except => [:options, :stats, :ping]
  load_and_authorize_resource
  skip_authorize_resource :only => [:options, :stats, :ping, :bulk_edit, :bulk_confirm, :bulk_perform]

  # GET /locations
  # GET /locations.json
  def index
    @filter_geography = params[:filter_geography] || nil
    if @filter_geography
      @locations = Location.includes(:survey).where(:geography => @filter_geography).order('name asc')
    else
      @locations = Location.includes(:survey).order('name asc').all
    end
    @geographies = Location.select(:geography).uniq.order('geography asc').map(&:geography)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new
    @surveys = Survey.order(:name)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
    @surveys = Survey.order(:name)
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    # Destroy votes associated with the locations
    @location.votes.destroy_all
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  # Bulk edit page
  def bulk_edit
    @geographies = Location.select(:geography).uniq.order('geography asc').map(&:geography)
    @surveys = Survey.order(:name)

    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  # Bulk Confirm
  def bulk_confirm
    @geography = params[:geography]
    @inactive_text = params[:inactive_text]
    @geo_text = @geography.empty? ? "all regions" : @geography

    @survey = Survey.find(params[:survey_id])

    @active = params[:active].to_i
    @active_text = @active == 1 ? "active" : "inactive"

    @update_survey = params[:update_survey]
    @update_active = params[:update_active]
    @update_inactive_text = params[:update_inactive_text]

  end

  def bulk_perform
    geography = params[:geography]
    inactive_text = params[:inactive_text]
    geo_text = geography.empty? ? "all regions" : geography
    survey = Survey.find(params[:survey_id])
    update_survey = params[:update_survey].empty? ? false : true
    update_active = params[:update_active].empty? ? false : true
    update_inactive_text = params[:update_inactive_text].empty? ? false : true
    success = false

    location_params = {}
    if update_survey
      location_params[:survey_id] = survey.id
    end

    if update_active
      location_params[:active] = params[:active]
    end

    if update_inactive_text
      location_params[:inactive_text] = params[:inactive_text]
    end


    if !location_params.empty? && survey
      if geography.empty?
        Location.update_all(location_params)
      else
        Location.where(:geography => geography).update_all(location_params)
      end
      success = true
    end
    respond_to do |format|
      if success
        format.html { redirect_to locations_url, notice: "The locations from #{geo_text} have all been updated." }
        format.json { head :no_content }
      else
        format.html { redirect_to locations_url, alert: "Sorry, something went wrong while bulk updating the locations" }
        format.json { render status: :unprocessable_entity }
      end
    end
  end


  #### IPAD FUNCTIONS
  def options
    @location = Location.find(params[:id])
    @survey = @location.survey
    respond_to do |format|
      format.html { render :partial => "options", :layout => false }
    end
  end

  # Get and display stats

  def stats
    @location = Location.find(params[:id])
    @survey = @location.survey

    all_votes = Vote.find_by_sql("select count(id) as vote_count, label from votes where survey_id = #{@survey.id} group by label")
    @votes = {}
    @max = 0
    @total = 0
    all_votes.each do |r|
      @votes[r.label] = r.vote_count.to_i
      if r.vote_count.to_i > @max
        @max = r.vote_count.to_i
      end
      @total += r.vote_count.to_i
    end
    if request.xhr?
      render :partial => 'stats_ajax'
    else

    end

  end

  # used to check if location is alive or not
  def ping
    @location = Location.find(params[:id])

    @location.update_attribute(:last_pinged, Time.now.utc)

    render :nothing => true,  :status => 200
  end
end

app/views/locations/_form.html.erb
<%= render :partial => 'layouts/notifications'%>

<%= form_for(@location, :html => {:class => 'aui'}) do |f| %>
  <fieldset>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'text' %>
    </div>
    <div class="field-group">
      <%= f.label :geography, 'Region' %>
      <%= f.text_field :geography, :class => 'text' %>
    </div>
    <% if @surveys %>
    <div class="field-group">
      <%= f.label :survey_id %>
      <%= f.select :survey_id, @surveys.collect {|s| [s.name, s.id]}, {:include_blank => 'No survey selected'}, :class => 'select' %>
    </div>
    <% else %>
    <div class="aui-message warning">
      <p>
        You haven't created any survey yet.
      </p>
    </div>
    <% end %>
    
    <div class="group">
      <legend><span>Location status</span></legend>
      <div class="checkbox">
        <%= f.check_box :active, :class => 'checkbox' %>
        <%= f.label :active %>
      </div>
    </div>
    
    <div class="field-group">
      <%= f.label :inactive_text, 'Image URL' %>
      <%= f.text_area :inactive_text, :class => 'textarea long-field', :rows => 8 %>
      <div class="description">Dimension should be 900x500px.</div>
    </div>
    <div class="buttons-container">
      <div class="buttons">
        <%= f.submit "Save", :class => 'button submit' %>
        <%= link_to 'Cancel', :back, :class => 'cancel' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/locations/_index_locations.html.erb
<p>
  <a href="#geography_filter" aria-owns="geography_filter" aria-haspopup="true" class="aui-button aui-dropdown2-trigger aui-style-default">
    <span class="fieldLabel">Region:</span> <%=@filter_geography || "All" %>
  </a>
</p>
<div id="geography_filter" class="aui-dropdown2 aui-style-default">
  <ul class="aui-list-truncate">
    <li><%=link_to "All", locations_path %></a></li>
  <% @geographies.each do |g| %>
    <li><%=link_to g, locations_path(:filter_geography => g)%></a></li>
  <% end %>
  </ul>
</div>

<table class="aui">
  <thead>
    <tr>
      <th>Name</th>
      <th>Geography</th>
      <th>Survey</th>
      <th>Active</th>
      <th>Last pinged</th>
      <th>Inactive image</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @locations.each do |location| %>
    <tr>
      <td><%= link_to location.name, location %></td>
      <td><%= location.geography %></td>
      <td>
        <% if location.survey %>
          <%= location.survey.name %>
        <% else %>
          <span class="aui-lozenge aui-lozenge-error aui-lozenge-subtle">NO SURVEY</span>
        <% end %>
      </td>
      <td>
        <% if location.active %>
          <span class="aui-icon aui-icon-success">Active</span>
        <% else %>
          <span class="aui-icon aui-icon-error">Inactive</span>
        <% end %>
      </td>
      <td>
        <% if location.last_pinged && location.last_pinged > (Time.now.utc - 5.minutes) %>
          <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-success">
        <% else %>
          <span class="aui-lozenge aui-lozenge-subtle aui-lozenge-error">
        <% end %>
        <%= location.last_pinged ? l(location.last_pinged, :format => :short) : 'Never pinged' %>
        </span>
      </td>
      <td>
        <% if location.inactive_text %>
        <%=truncate(location.inactive_text, :length => 50)%>
        <% end %>
      </td>
      <td>
        <%= link_to 'Edit', edit_location_path(location) %>
        |
        <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/locations/_index_nolocations.html.erb
<h2>Create your first iPad location!</h2>
<p>
  A location can correspond to a country, a city or a specific spot in your office.
</p>
<p> 
  After associating your iPads with a particular locations you will be able to control<br />
  and display survey from this administration interface.
</p>
<p>
  <%= link_to 'New Location', new_location_path, :class => 'aui-button' %> 
</p>

app/views/locations/_options.html.erb
<% if @location.active && @survey %>
  <h1><%=@survey.question%></h1>
  <div id="answers-div">
  	<% if @survey.scale == 2 %>
  		<%=link_to image_tag('0-' + @survey.visual + '.png'), '#', :onclick => "return saveVote('0', #{@survey.id})"%>
  		<%=link_to image_tag('4-' + @survey.visual + '.png'), '#', :onclick => "return saveVote('4', #{@survey.id})"%>
  	<% elsif @survey.scale == 5 %>
  	 	<% 0.upto(4) do |i| %>
  			<%=link_to image_tag(i.to_s + '-' + @survey.visual + '.png'), '#', :onclick => "return saveVote('#{i}', #{@survey.id})"%>
  		<% end %>
  	<% else %>
  		Sorry, an error occurred
  	<% end %>
  </div>
<% else %>
  <% if @location.inactive_text  && !@location.inactive_text.empty?  %>
  <div id="idle-image">
    <%=raw @location.inactive_text%>
  </div>
  <% else %>
  <div id="idle">
    <%=image_tag 'atlassian.png'%>
  
    <% if false %>
    <div id="quote">
      <p><%=@location.inactive_text%></p>
      <%=image_tag 'phrase-bg.png' %>
    </div>
    <% end %>
  </div>
  <% end %>
<% end %>

app/views/locations/_stats_ajax.html.erb
<h2><%=@survey.question%></h2>
<table class="survey">
	<% if @survey.scale == 2 %>
		<tr>	
		<%['0', '4'].each do |option|%>
			
				<td class="positioned" valign="bottom" style="vertical-align:bottom">
					<% if @votes[option] %>
					<div style="height:<%=((@votes[option] * 200)/@max) + 20%>px" class="stat-block color-<%=option%>">

						
					</div>
					<% else %>
					<% end %>
				</td>
			
		<% end %>
		</tr>
		<tr>	
		<%['0', '4'].each do |option|%>
			
				<td class="positioned" valign="bottom" style="vertical-align:bottom">
					<%=image_tag(option.to_s + '-'  + @survey.visual + '.png')%>
				</td>
			
		<% end %>
		</tr>
		<tr>	
		<%['0', '4'].each do |option|%>
			
				<td class="positioned" valign="bottom" style="vertical-align:bottom">
					<%= (@votes[option].to_f*100/@total.to_f).round%>%
				</td>
			
		<% end %>
		</tr>
		
	<% elsif @survey.scale == 5 %>
		<tr>
		<% 0.upto(4) do |option| %>
		
			
				<td class="positioned" valign="bottom" style="vertical-align:bottom">
					<% if @votes[option.to_s] %>
					<div style="height:<%=((@votes[option.to_s] * 200)/@max) + 20%>px" class="stat-block color-<%=option%>">
	
					</div>
					<% else %>
					<% end %>
				</td>
			
		<% end %>
		</tr>
		<tr>	
		<% 0.upto(4) do |option| %>
			
				<td class="positioned" valign="bottom" style="vertical-align:bottom">
					<%=image_tag(option.to_s + '-'  + @survey.visual + '.png')%>
				</td>
			
		<% end %>
		</tr>
		<tr>	
		<% 0.upto(4) do |option| %>
			
				<td class="positioned" valign="bottom" style="vertical-align:bottom">
					<%= (@votes[option.to_s].to_f*100/@total.to_f).round%>%
				</td>
			
		<% end %>
		</tr>
	<% end %>
	
</table>

app/views/locations/bulk_confirm.html.erb
<% content_for :aui_layout do %>
  <body class="ui-layout aui-theme-default aui-page-focused aui-page-focused-medium">  
<% end %>

<h2>Confirm bulk editing</h2>

<%= render :partial => 'layouts/notifications'%>

<%= form_tag(bulk_perform_locations_path, :class => 'aui') do |f| %>
  <%= hidden_field_tag :geography, @geography %>
  <%= hidden_field_tag :survey_id, @survey.id %>
  <%= hidden_field_tag :active, @active %>
  <%= hidden_field_tag :inactive_text, @inactive_text %>
  <%= hidden_field_tag :update_survey, @update_survey %>
  <%= hidden_field_tag :update_active, @update_active %>
  <%= hidden_field_tag :update_inactive_text, @update_inactive_text %>
  <p>
    Are you sure that you want to perform the following changes for surveys from <%=@geo_text%>:
  </p>
  <ul>
    <% if @update_survey %>
    <li>Change survey to <strong><%=@survey.name%></strong></li>
    <% end%>
    <% if @update_active %>
    <li>Change activation status to <strong><%= @active_text %></strong></li>
    <% end%>
    <% if @update_inactive_text %>
    <li>Change inactive image URL to <strong><%= @inactive_text %></strong></li>
    <% end%>
  </ul>
  <div class="buttons-container">
    <div class="buttons">
      <%= submit_tag "Bulk edit", :class => 'aui-button aui-button-primary' %>
      <%= link_to "Back", :back, :class => 'aui-button aui-button-link' %>
      <%= link_to "Cancel", locations_path, :class => 'aui-button aui-button-link' %>
    </div>
  </div>
<% end %>

app/views/locations/bulk_edit.html.erb
<% content_for :aui_layout do %>
  <body class="ui-layout aui-theme-default aui-page-focused aui-page-focused-medium">  
<% end %>

<h2>Bulk edit locations</h2>

<%= render :partial => 'layouts/notifications'%>

<%= form_tag(bulk_confirm_locations_path, :class => 'aui') do |f| %>
  <fieldset>
    <div class="field-group">
      <%= label_tag :geography, 'Region' %>
      <select class="select" name="geography">
        <option value="">All</option>
        <% @geographies.each do |g| %>
        <option value="<%= g %>"><%= g %></option>
        <%end %>
      </select>
    </div>

    <h3>Survey updates</h3>
    <div class="group">
      <legend><span>Update survey</span></legend>
      <div class="checkbox">
        <%= check_box_tag :update_survey, 1, false, :class => 'checkbox' %>
        <%= label_tag 'Bulk change linked survey' %>
        <div class="description">Check this field to update the linked survey of all selected locations</div>
      </div>
    </div>
    <div class="field-group">
      <%= label_tag :survey_id %>
      <%= select_tag :survey_id, options_from_collection_for_select(@surveys, "id", "name"), :class => 'select' %>
    </div>
    
    <h3>Activation status updates</h3>
    <div class="group">
      <legend><span>Update activation status</span></legend>
      <div class="checkbox">
        <%= check_box_tag :update_active, 1, false, :class => 'checkbox' %>
        <%= label_tag 'Bulk change activation tatus' %>
        <div class="description">Check this field to update the activation status of all selected locations</div>
      </div>
    </div>
    <div class="field-group">
      <%= label_tag :status %>
      <select class="select" name="active">
        <option value="1">Active</option>
        <option value="0">Inactive</option>
      </select>
    </div>
    
    <h3>Inactive image URL</h3>
    <div class="group">
      <legend><span>Update inactive image</span></legend>
      <div class="checkbox">
        <%= check_box_tag :update_inactive_text, 1, false, :class => 'checkbox' %>
        <%= label_tag 'Bulk change inactive image URL' %>
        <div class="description">Check this field to update the inactive image URL of all selected locations</div>
      </div>
    </div>
    <div class="field-group">
      <%= label_tag :inactive_text, 'Image URL' %>
      <%= text_field_tag :inactive_text, '', :class => 'text long-field'%>
    </div>
    
    
  </fieldset>
  <div class="buttons-container">
    <div class="buttons">
      <%= submit_tag "Bulk edit", :class => 'aui-button aui-button-primary' %>
      <%= link_to "Cancel", locations_path, :class => 'aui-button aui-button-link' %>
    </div>
  </div>
<% end %>

app/views/locations/edit.html.erb
<% content_for :page_title do %>
  <h1>Edit <%=@location.name%></h1>
<% end %>

<% content_for :page_header_image do %>
  <%= image_tag "project-avatar-blue-48@2x.png" %>
<% end %>

<%= render 'form' %>

app/views/locations/index.html.erb
<% content_for :page_title do %>
  <h1>Locations</h1>
<% end %>

<% content_for :page_header_image do %>
  <%= image_tag "project-avatar-blue-48@2x.png" %>
<% end %>

<% if @locations.size > 0 %>

  <% content_for :page_actions do %>
    <div class="aui-buttons">
      <%= link_to 'New Location', new_location_path, :class => 'aui-button' %>
      <%= link_to 'Bulk Edit', bulk_edit_locations_path, :class => 'aui-button' %>
    </div>
  <% end %>

  <%= render :partial => 'layouts/notifications'%>

  <%= render :partial => 'index_locations' %>
<% else %>
  <%= render :partial => 'index_nolocations' %>
<% end %>

app/views/locations/new.html.erb
<% content_for :page_title do %>
  <h1>New location</h1>
<% end %>

<% content_for :page_header_image do %>
  <%= image_tag "project-avatar-blue-48@2x.png" %>
<% end %>

<%= render 'form' %>

app/views/locations/show.html.erb
<% content_for :page_title do %>
  <ol class="aui-nav aui-nav-breadcrumbs">
    <li><%= link_to "Locations", locations_path %></li>
  </ol>
  <h1><%=@location.name%></h1>
<% end %>

<% content_for :page_header_image do %>
  <%= image_tag "project-avatar-blue-48@2x.png" %>
<% end %>

<% content_for :page_actions do %>
  <div class="aui-buttons">
    <%= link_to 'Edit', edit_location_path(@location), :class => 'aui-button' %>
    <%= link_to 'View votes', votes_path(:location_id => @location.id), :class => 'aui-button' %>
    <%= link_to 'Destroy', @location, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'aui-button aui-button-link' %>
  </div>
<% end %>

<%= render :partial => 'layouts/notifications'%>

<p>
  <b>Geography:</b>
  <%= @location.geography %>
</p>

<p>
  <b>Survey:</b>
  <% if @location.survey %>
    <%= link_to @location.survey.name, @location.survey %>
  <% else %>
    <span class="aui-lozenge aui-lozenge-error aui-lozenge-subtle">NO SURVEY</span>
  <% end %>
</p>

<p>
  <b>Active:</b>
  <%= @location.active %>
</p>

<p>
  <b>Inactive text:</b>
  <%= @location.inactive_text%>
</p>