config/routes.rb
Moodapp::Application.routes.draw do
  resources :surveys

  root :to => 'locations#index'
  #match 'dashboard' => 'home#dashboard'

  devise_for :users
  resources :users
  put '/user_admin' => 'users#update', :as => 'user_admin'

  resources :locations do
    collection do
      get 'bulk_edit'
      post 'bulk_confirm'
      post 'bulk_perform'
    end
    member do
      get 'options'
      get 'stats'
      get 'ping'
    end
  end

  resources :locations

  resources :votes

  get "/ipad" => "ipad#index", :as => :ipad
  get "/ipad/configure" => "ipad#configure", :as => :ipad_configuration
  get "/ipad/new_session" => "ipad#new_session"
  post "/ipad/sign_in" => "ipad#sign_in"
  post "/ipad/save_configuration" => "ipad#save_configuration"
  delete "/ipad/logout" => "ipad#logout"


end

app/views/layouts/_header.html.erb
<header id="header" role="banner">
  <nav class="aui-header aui-dropdown2-trigger-group" role="navigation">
    <div class="aui-header-inner">
      <div class="aui-header-primary">
        <h1 id="logo" class="aui-header-logo logo-moodapp"><a href="/"><span class="aui-header-logo-device">Atlassian Moodapp</span></a></h1>
        <% if user_signed_in? %>
        <ul class="aui-nav">
          <li><%=link_to "Locations", locations_path  %></li>
          <li><%=link_to "Surveys", surveys_path  %></li>
          <% if can? :read, User %>
          <li><%=link_to "Users", users_path  %></li>
          <% end %>
          <% if can? :read, Vote %>
          <li><%=link_to "Votes", votes_path  %></li>
          <% end %>
          <li><%=link_to "iPad Configuration", ipad_configuration_path  %></li>
        </ul>
        <% end %>
      </div>
      <% if user_signed_in? %>
      <div class="aui-header-secondary">
        <ul class="aui-nav">
          <li>
            <a href="#profileDropDown" aria-owns="profile-dropdown" aria-haspopup="true" class="aui-dropdown2-trigger" aria-controls="profile-dropdown">
              <%=current_user.email%>
            </a>
            <div class="aui-dropdown2 aui-style-default aui-dropdown2-in-header" id="profile-dropdown" aria-hidden="true">
              <div class="aui-dropdown2-section">
                <ul>
                  <li><%= link_to('Settings', edit_registration_path(current_user), :class => 'active') %></li>
                  <li><%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'active') %></li>
                </ul>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <% end %>
    </div>
  </nav>
</header> <!-- #header -->

app/views/layouts/_notifications.html.erb
<% if notice %>
  <div class="aui-message success">
    <p><%= notice %></p>
  </div>
<% end %>

<% if alert %>
  <div class="aui-message warning">
    <p><%= alert %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoodApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<% if content_for?(:aui_layout) %>
  <%= yield :aui_layout %>
<% else %>
  <body class="aui-layout aui-theme-default aui-page-fixed">
<% end %>
  <div id="page">

    <%= render :partial => 'layouts/header'%>

    <section id="content" role="main">
      <header class="aui-page-header">
        <div class="aui-page-header-inner">
          <% if content_for?(:page_header_image)%>
          <div class="aui-page-header-image">
            <div class="aui-avatar aui-avatar-xlarge aui-avatar-project">
              <div class="aui-avatar-inner">
                <%= yield :page_header_image %>
              </div>
            </div>
          </div>
          <% end %>
          <div class="aui-page-header-main">
            <%= yield :page_title %>
          </div>
          <% if content_for?(:page_actions)%>
          <div class="aui-page-header-actions">
            <%= yield :page_actions %>
          </div>
          <% end %>
        </div>
      </header> <!-- .aui-page-header -->
      <div class="aui-page-panel">
        <div class="aui-page-panel-inner">
          <section class="aui-page-panel-content">

            <%= yield %>

          </section> <!-- .aui-page-panel-content -->
        </div> <!-- .aui-page-panel-inner -->
      </div> <!-- .aui-page-panel -->
    </section> <!-- #content -->

  </div> <!-- #page -->
</body>
</html>

app/views/layouts/ipad.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoodApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--  Mobile Viewport Fix
  j.mp/mobileviewport & davidbcalhoun.com/2010/viewport-metatag
  device-width : Occupy full width of the screen in its current orientation
  initial-scale = 1.0 retains dimensions instead of zooming out if page height > device height
  maximum-scale = 1.0 retains dimensions instead of zooming in if page width < device width
  -->
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
  <!-- full-screen on mobile safari - only after added to home screen -->
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <!-- translucent status bar - only after added to home screen -->
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
</head>
<body class="ui-layout aui-theme-default aui-page-focused aui-page-focused-medium">  
  <div id="page">
    
    <header id="header" role="banner">
      <nav class="aui-header aui-dropdown2-trigger-group" role="navigation">
        <div class="aui-header-primary">
          <h1 id="logo" class="aui-header-logo  logo-moodapp"><a href="/"><span class="aui-header-logo-device">Atlassian Moodapp</span></a></h1>
          <% if cookies[:ipad_admin] %>
          <ul class="aui-nav">
            <li><%= link_to('Logout', '/ipad/logout', :method => :delete) %></li>
          </ul>
          <% end %>
        </div>
      </nav>
    </header> <!-- #header -->
    
    <section id="content" role="main">
      <div class="aui-page-panel">
        <div class="aui-page-panel-inner">
          <section class="aui-page-panel-content">
            
            <%= yield %>
    
          </section> <!-- .aui-page-panel-content -->
        </div> <!-- .aui-page-panel-inner -->
      </div> <!-- .aui-page-panel -->
    </section> <!-- #content -->
        
  </div> <!-- #page -->
</body>
</html>